# Generated by Django 2.2.5 on 2020-11-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogNewsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
